export default {
    btn: {
        load_new: 'Load New',
        delete_all: 'Delete All',
        back: 'Back',
        back_to_login: 'Back to login',
        save: 'Save',
        delete: 'Delete',
        download: 'Download',
        send: 'Send',
        retry: 'Retry',
        add: 'Add',
        cancel: 'Cancel',
        confirm: 'Confirm',
        yes_delete: 'Yes, Delete',
        yes_i_agree: 'Yes, I Agree',
        close: 'Close',
        edit: 'Edit',
        remove: 'Remove',
        yes_remove: 'Yes, remove',
        send_code: 'Send Code',
        register: 'Register',
        register_no_account: 'Don\'t have an account? Register',
        forgot_password: 'Forgot Password?',
        already_have_account: 'Already have an account? Login',
        location_permissions: 'Location Permissions',
        notification_permissions: 'Notification Permissions',
        account_settings: 'Account Settings',
        about_us: 'About Us',
        contact_us: 'Contact Us',
        language: 'Language',
        help_center: 'Help Center',
        frequent_questions: 'Frequent Questions',
        feedback: 'Feedback',
        privacy_terms: 'Privacy & Terms',
        admin: 'Admin',
        admin_sub: 'Manage your data',
        edit_profile: 'Edit Profile',
        edit_profile_sub: 'Update your information',
        settings_privacy: 'Settings & Privacy',
        settings_privacy_sub: 'Permissions, settings, privacy',
        log_out: 'Log Out',
        log_out_sub: 'Log out or change accounts',
        login: 'Login',
        verify: 'Verify',
        sign_up: 'Sign Up',
        dark_mode: 'Dark Mode',
        learn_more: 'Learn More',
        content: 'Content',
        back_to_app: 'To App',
        send_password_reset: 'Send Password Reset',
        deactivate: 'Deactivate',
        reactivate: 'Re-Activate',
        confirm_request: 'Confirm Request'
    },
    notify: {
        no_audio: 'No audio',
        success: 'Success',
        check_your_email: 'Please check your email',
        error_try_again: 'Error, try again',
        exists_already: 'Exists already',
        email_in_use: 'Email already in use',
        phone_in_use: 'Phone already in use',
        username_in_use: 'Username already in use',
        already_linked: 'Your account is already linked',
        agree_to_terms: 'You must agree to terms before continuing',
        validate_your_phone: 'You must validate your phone number before continuing',

        not_enough_admins: 'Chat must have at least one admin.',

        gps_permission_denied: 'Permission Location Denied',
        gps_permission_prompt: 'Permission Location Prompt',

        file_uploaded_error_type: 'Error, not an appropriate file type',

        notifications_not_supported: 'Notifications are not supported',
        notifications_error: 'Error with your notifications',

        pin_no_match: 'This PIN does not match',

        are_you_sure: 'Are you sure?',
        please_confirm_delete: 'Please confirm you wish to delete your account and all data. This is not reversible.'
    },
    heading: {
        login_phone: `Provide your phone number to login`,
        login_email: `Provide your email address to login`,
        signup_phone: `Provide your phone number to create an account`,
        signup_email: `Provide your email address to create an account`,
        cant_receive_sms_code: 'Can\'t receive code? Sign in through email.',
        we_sent_you_sms_code: 'We sent you a SMS code',
        forgot_password: 'Forgot Password',
        edit_profile: 'Profile',
        change_language: 'Change language',
        add_email: 'Add Your Email Address',
        register: 'Register For Free',
        change_email_address: 'Change Email Address',
        change_email_address_caption: 'To change your email, please provide your password.',
        change_password: 'Change Password',
        change_password_caption: 'To change your password, please provide your current password.',
        change_phone_number: 'Change Phone Number',
        change_phone_number_caption: 'To change your phone, please provide your OTP sent to you.',
        delete_account: 'Delete Account',
        delete_account_caption: 'Your entire profile and data will be permanently removed.',
        friends: 'Friends',
        login: 'Login'
    },
    form: {
        first_name: 'First Name',
        last_name: 'Last Name',
        name: 'Name',
        username: 'Username',
        description: 'Description',
        hometown: 'Hometown',
        country: 'Country',
        email: 'Email',
        phone: 'Phone',
        message: 'Message',
        password: 'Password',
        confirm_password: 'Confirm Password',
        current_password: 'Current Password',
        new_password: 'New Password',
        search_for_address: 'Search for your address',
        search: 'Search',
        search_friends: 'Search Friends...',
        code: 'Code',
        company: 'Company',
        tags: 'Tags',
        images: 'Images',
        website: 'Website',
        address: 'Address',
        city: 'City',
        province: 'Province',
        postal_code: 'Postal Code',
        published: 'Published',
        logo: 'Logo',
        featured_image: 'Featured Image',
        featured_category: 'Featured Category',
        tag: 'Tag',
        title: 'Title',
        content: 'Content',
        using_markdown: 'Is content using markdown?',
        learn_more_url: 'Learn More Url',
        learn_more_label: 'Learn More Label',
        is_admin: 'Is Admin',
        created_at: 'Created At',
        location_enabled: 'Location Enabled',
        share_location: 'Share Location',
        pin: 'PIN',
        filter_by: 'Filter By'
    },
    email: {
        contact_h1: 'You were contacted'
    },
    chats: {
        page_h1: 'Your Chats',
        no_chats: 'No chats to display',
        no_messages: 'Send the first message!',
        label_message: 'Message',
        select_friend_first: 'Select a friend first',
        no_friends: 'You have no friends to chat with.',
        new_chat: 'New Chat',
        start_chat: 'Start Chat',
        select_friends: 'Select friends you wish to chat with',
        add_friend: 'Add Friend',
        remove_friend: 'Remove Friend',
        confirm_remove_friend: 'Please confirm you wish to remove as a friend.',
        chat_name: 'Chat Name',
        rename_chat: 'Rename Chat',
        send_message: 'Send A Message',
        enter_pin: 'Enter in your friend\'s PIN',
        add_member: 'Add Member',
        view_members: 'View Members',
        remove_chat: 'Remove Chat',
        audio_expired: 'Audio Clip Has Expired',
        you_replied_to: 'You replied to',
        replying_to: 'Replying to',
        forward: 'Forward',
        video_not_supported: 'Videos not supported',
        forward_a_message: 'Forwarded a message'
    },
    notifications: {
        heading: 'Notifications',
        sub_heading: 'Stay up-to-date',
        caught_up: 'You\'re all caught up!',
        chat_notification: 'Chat Notification',
        new_friend_request: 'New Friend Request',
        friend_request_approved: 'Friend Request Approved',
        requested_to_be_your_friend: 'requested to be your friend.',
        accepted_your_friendship: 'accepted your friendship.',
        requested_to_check_in: 'You have been requested to check-in by',
        contact_them: 'Contact them by phone or text message.',
        this_is_emergency_alarm_from: 'This is an emergency alarm from',
        checked_in_title: 'Checked-In',
        has_checked_in: ' has checked-in.',
        welcome_title: 'Welcome',
        welcome_body: 'Welcome to MyShout',
        archive: 'Archive',
        archive_all: 'Archive All Notifications'
    },
    gps: {
        gps: 'GPS',
        user_no_location: 'User has not updated their location yet.',
        rationale_title: 'Allow My Shout to access this device\'s location even when closed or not in use.',
        rationale_message: 'This app collects location data to notify your family and emergency contacts in case of emergency.',
        rationale_positive_action: 'Change to Always Allow',
        rationale_negative_action: 'Cancel'
    },
    contacts: {
        invite_friends: 'Invite Friends',
        no_contacts: 'You have no contacts',
        find_friends: 'Find Friends',
        search_friends: 'Search Friends',
    },
    onboarding: {
        terms_text: 'By signing up you agree to our',
        terms_btn: 'Privacy Policy and Terms',
        enable_location_permissions_heading: 'Your Location',
        enable_location_permissions_sub: 'MyShout collects location data to enable emergency buttons, in-app mapping.',
        enable_notification_permissions_heading: 'Notifications',
        enable_notification_permissions: 'Notifications may include alerts, sounds and icon badges. These can be configured in settings.',
        add_phone_number_heading: 'What is your phone number?',
        add_phone_number_sub: 'Your phone number is vital for alerting your friends and family in case of emergency.',
        add_photo_heading: 'Great! How about a profile photo?',
        add_photo_sub: 'Let others see who you are.',
        profile_setup_heading: 'Welcome!',
        profile_setup_sub: 'Looks like you\'re new here, let\'s setup your profile.',
        register_to_get_started: 'Register to get started',
        already_have_account: 'Already Have An Account? Login!',
        agree_to_terms: 'Yes, I agree to terms',
        heading_sign_in: 'Welcome Back! Sign in',
        btn_no_account: 'Don\'t have an account? Sign Up!',
        thank_you_heading: 'You\'re Done!',
        thank_you_sub: 'Thanks for setting up your profile.',
        username_heading: 'What should we call you?',
        username_sub: 'Set a display name for others to know who they are talking to.',
        email_sub: 'Provide your email address. This will be used to recover your account if your phone number is lost.',
        country_sub: `Let us know where you are from.`,
        how_did_you_hear: `How did you hear about us?`,
        error_wrong_password: `The password inputted is incorrect.`,
        error_user_not_found: `No user exists. Please create a new account.`,
        error_email_in_use: `The email address is already in use.`,
        location_description: 'MyShout uses location data to notify your emergency contacts, and an admin, if emergency is at it\'s highest level. When you click an emergency button, this will use your latest GPS location data and notify your contacts. Your location is always being collected for emergency notifications even when the app is running in the background. Location access is only used for maps to show your contacts where you are, and to send notifications to selected contacts.',
        location_requirements_1: 'When clicking an emergency button to notify your emergency contacts',
        location_requirements_2: 'Notifying your emergency contacts',
        location_requirements_3: 'Enabling in-app mapping',
        location_requirements_4: 'Location is captured even while running in the background',
        notification_requirements_1: 'For new friend requests',
        notification_requirements_2: 'For chat notifications',
        notification_requirements_3: 'For emergency alerts',
        notification_requirements_4: 'Your microphone will only be used for Shout Alerts'
    },
    page: {
        not_found_heading: '404',
        not_found_text: 'Nothing found',


        welcome: 'Welcome to your app',
        contact_intro: 'Feel free to reach out to us with any questions you might have.',
        status_heading_success: 'Your account is active!',
        status_heading_error: 'Your account is not active!',

        faq: 'FAQ',
        home_h1: 'Emergency Alerts',
        home_p: 'By pressing any of the following alerts, you\'ll be notifying all your emergency contacts your last known location.'
    },
    permission: {
        yes_status: 'Your status is active',
        no_status: 'You cannot access that, your status is not active.',
        no_user_profile: 'You do not have permission to view their profile.',
        no_view_location: 'Your are not able to view their location.'
    },
    chat: {
        admins: 'Admins',
        members: "Members",
        add_member: "Add Member",
        mute_notifications: 'Mute Notifications',
        unmute_notifications: 'Unmute Notifications',
        view_profile: 'View Profile',
        leave_group: 'Leave Group',
        remove_from_group: 'Remove From Group',
        remove_from_chat: 'Remove From Chat',
        leave_chat: 'Leave Chat',
        add_title: 'Add title',
        add_group_description: 'Add group description',
        error_updating: 'There was a problem updating...',
        action: 'Actions',
        reply_to_message: 'Reply To Message',
        forward_message: 'Forward Message',
        message_deleted: 'This message was deleted',
        delete_for_me: 'Delete For Me',
        delete_for_everyone: 'Delete For Everyone',
        info: 'Info',
        thread: 'View Thread',
        message_thread: 'Message Thread',
        forward_to: 'Forward To',
        recent_chats: 'Recent Chats',
        download_file: 'Download File',
        refresh_chat: 'Refresh Chat',
        no_messages: 'This chat has no messages'
    },

    no_results: 'No results',
    actions: 'Actions',
    is_loading: 'Loading...',
    copyright: 'Copyright',
    you_are_currently_logged_in: 'You are currently logged in!',
    you_are_currently_offline: 'Uh Oh! It looks like you are offline.',
    not_supposed_to_be_here: 'Looks like you are not supposed to be here.',
    page_not_found: 'Page not found',
    error_occurred: 'An error occurred',
    refresh_data: 'Try Refresh Data',

    profile: 'Profile',
    view_profile: 'View Profile',
    view_more: 'View More',

    know_your_safe: 'Let family & friends know you\'re safe!',
    include_email: 'Let\'s include your email for a backup',
    new_friend_request: 'New Friend Request',
    requested_to_be_your_friend: 'requested to be your friend.',
    skip_for_now: 'Skip for now',
    start_chatting: 'Provide your phone number to start chatting',
    security_pin_heading: 'Security Pin',
    security_pin_description: 'Provide your secret PIN to those you wish to add you as a friend on MyShout.',

    emergency_contacts_heading: 'Emergency Contacts',
    emergency_contacts_description: 'Required, share you location with all emergency contacts.',
    all_friends_header: 'All Friends',
    all_friends_description: 'Optionally, share your location with all approved friends.',

    must_be_emergency_contact: 'You must be their emergency contact to view alerts',
    you_have_no_alerts: 'You have no alerts',

    verify_account: 'Please login again to verify your account',
    already_verified: 'Your account is already linked with an email',

    remove_friend: 'Remove As Friend',
    friendship_is: 'friendship is',
    location: 'Location',
    alerts: 'Alerts',
    emergency: 'Emergency',
    friends: 'Friends',
    settings: 'Settings',

    alert: 'Alert',
    accident: 'Accident',
    kidnapping: 'Kidnapping',
    robbery: 'Robbery',
    shout: 'Shout',

    alert_details: 'Alert Details',
    accident_alert: 'Accident Alert',
    kidnapping_alert: 'Kidnapping Alert',
    robbery_alert: 'Robbery Alert',
    shout_alert: 'Shout Alert',
    your_shout_alert: 'Your Shout alert has been sent',
    hold_for: 'Hold To Send A 5 Second Audio Record',
    alert_sent: 'Alert sent',
    notified_emergency_contacts_accident: 'We have notified your emergency contacts of your accident. Please call them as soon as you have the opportunity.',
    notified_emergency_contacts_kidnapping: 'We have notified your emergency contacts of your kidnapping. Please call them as soon as you have the opportunity.',
    notified_emergency_contacts_robbery: 'We have notified your emergency contacts of your robbery. Please call them as soon as you have the opportunity.',


    recording: 'Recording',

    previous: 'Previous',
    next: 'Next',

    sharing_your_location_sub: 'Sharing your location is critical for emergency contacts to monitor your location.',
    receive_notifications_sub: 'Receive notifications when a friend is in trouble, or a new chat message has been received.',

    check_in: 'Check-In',
    request_safe_check_in: 'Request safe check-in',
    confirm_they_are_safe: 'We will send an alert to confirm they are safe.',
    remove_as_emergency_contact: 'Remove as emergency contact',
    add_as_emergency_contact: 'Add as emergency contact',
    no_longer_receive_alerts: 'They will no longer receive alerts when you are in trouble.',
    yes_longer_receive_alerts: 'They will receive alerts when you are in trouble.',
    view_on_list: 'View on list',

    no_emergency_friends: 'You have no emergency friends',

    use_email_address: 'Use Email Address',
    use_phone_number: 'Use Phone Number'

}
