export default {
    btn: {
        load_new: 'Cargar nueva',
        delete_all: 'Eliminar todos',
        back: 'atrás',
        back_to_login: 'Atrás para iniciar sesión',
        save: 'Guardar',
        delete: 'Borrar',
        download: 'Descargar',
        send: 'Enviar',
        retry: 'Rever',
        add: 'Agregar',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        yes_delete: 'Sí, Eliminar',
        yes_i_agree: 'Sí estoy de acuerdo',
        close: 'Cerca',
        edit: 'Editar',
        remove: 'Remover',
        yes_remove: 'Si, eliminar',
        send_code: 'Enviar código',
        register: 'Registro',
        register_no_account: '¿No tienes una cuenta? Registro',
        forgot_password: '¿Has olvidado tu contraseña?',
        already_have_account: '¿Ya tienes una cuenta? Acceso',
        location_permissions: 'Permiso de ubicación',
        notification_permissions: 'Permiso de notificación',
        account_settings: 'Configuración de la cuenta',
        about_us: 'Sobre nosotras',
        contact_us: 'Contacta con nosotras',
        language: 'Idioma',
        help_center: 'Centro de ayuda',
        frequent_questions: 'Preguntas Frecuentes',
        feedback: 'Retroalimentación',
        privacy_terms: 'Privacidad y términos',
        admin: 'Administradora',
        admin_sub: 'Administra tus datos',
        edit_profile: 'Editar perfil',
        edit_profile_sub: 'Actualiza tu informacion',
        settings_privacy: 'Configuración y privacidad',
        settings_privacy_sub: 'Permisos, configuración, privacidad',
        log_out: 'Cerrar sesión',
        log_out_sub: 'Cerrar sesión o cambiar cuentas',
        login: 'Acceso',
        verify: 'Verificar',
        sign_up: 'Regístrate',
        dark_mode: 'Modo oscuro',
        learn_more: 'Aprende más',
        content: 'Contenido',
        back_to_app: 'A la aplicación',
        send_password_reset: 'Enviar restablecimiento de contraseña',
        deactivate: 'Desactivar',
        reactivate: 'Reactivar',
        confirm_request: 'Confirmar petición'
    },
    notify: {
        no_audio: 'Sin audio',
        success: 'Éxito',
        check_your_email: 'Por favor revise su correo electrónico',
        error_try_again: 'Error, inténtalo de nuevo',
        exists_already: 'ya existe',
        email_in_use: 'Correo electrónico ya en uso',
        phone_in_use: 'Teléfono ya en uso',
        username_in_use: 'Nombre de usuario ya está en uso',
        already_linked: 'Tu cuenta ya está vinculada',
        agree_to_terms: 'Debe aceptar los términos antes de continuar',
        validate_your_phone: 'Debe validar su número de teléfono antes de continuar',

        not_enough_admins: 'El chat debe tener al menos un administrador.',

        gps_permission_denied: 'Ubicación de permiso denegada',
        gps_permission_prompt: 'Solicitud de ubicación de permiso',

        file_uploaded_error_type: 'Error, no es un tipo de archivo apropiado',

        notifications_not_supported: 'Las notificaciones no son compatibles',
        notifications_error: 'Error con tus notificaciones',

        pin_no_match: 'Este PIN no coincide',

        are_you_sure: 'Estas segura',
        please_confirm_delete: 'Confirme que desea eliminar su cuenta y todos los datos. Esto no es reversible.'
    },
    heading: {
        login_phone: `Proporciona tu número de teléfono para iniciar sesión`,
        login_email: `Proporciona tu dirección de correo electrónico para iniciar sesión`,
        signup_phone: `Proporcione su número de teléfono para crear una cuenta`,
        signup_email: `Proporciona tu dirección de correo electrónico para crear una cuenta`,
        cant_receive_sms_code: '¿No puedes recibir el código? Iniciar sesión por correo electrónico',
        we_sent_you_sms_code: 'Te enviamos un código SMS',
        forgot_password: 'Has olvidado tu contraseña',
        edit_profile: 'Perfil',
        change_language: 'Cambiar idioma',
        add_email: 'Agregue su dirección de correo electrónico',
        register: 'Registrate gratis',
        change_email_address: 'Cambiar dirección de correo electrónico',
        change_email_address_caption: 'Para cambiar su correo electrónico, proporcione su contraseña.',
        change_password: 'Cambiar contraseña',
        change_password_caption: 'Para cambiar tu contraseña, proporciona tu contraseña actual.',
        change_phone_number: 'Cambiar número de teléfono',
        change_phone_number_caption: 'Para cambiar su teléfono, proporcione la OTP que se le envió.',
        delete_account: 'Eliminar cuenta',
        delete_account_caption: 'Todo tu perfil y datos se eliminarán permanentemente.',
        friends: 'Amigas',
        login: 'Acceso'
    },
    form: {
        first_name: 'Nombre',
        last_name: 'Apellido',
        name: 'Nombre',
        username: 'Nombre de usuario',
        description: 'Descripción',
        hometown: 'Ciudad de origen',
        country: 'País',
        email: 'Correo electrónico',
        phone: 'Teléfono',
        message: 'Mensaje',
        password: 'Clave',
        confirm_password: 'Confirmar contraseña',
        current_password: 'Contraseña actual',
        new_password: 'Nueva contraseña',
        search_for_address: 'Busca tu dirección',
        search: 'Búsqueda',
        search_friends: 'Buscar amigas...',
        code: 'Código',
        company: 'Compañía',
        tags: 'Etiquetas',
        images: 'Imágenes',
        website: 'Sitio web',
        address: 'Dirección',
        city: 'Ciudad',
        province: 'Provincia',
        postal_code: 'Código postal',
        published: 'Publicada',
        logo: 'Logo',
        featured_image: 'Foto principal',
        featured_category: 'Foto principal',
        tag: 'Etiqueta',
        title: 'Título',
        content: 'Contenido',
        using_markdown: '¿El contenido está usando Markdown?',
        learn_more_url: 'Más información URL',
        learn_more_label: 'Más información Etiqueta',
        is_admin: 'es administrador',
        created_at: 'Creado en',
        location_enabled: 'Ubicación habilitada',
        share_location: 'Comparte ubicacion',
        pin: 'PIN',
        filter_by: 'Filtrado por'
    },
    email: {
        contact_h1: 'You were contacted'
    },
    chats: {
        page_h1: 'Tus chats',
        no_chats: 'No hay chats para mostrar',
        no_messages: '¡Envía el primer mensaje!',
        label_message: 'Mensaje',
        select_friend_first: 'Selecciona una amiga primero',
        no_friends: 'No tienes amigas para chatear.',
        new_chat: 'Nuevo chat',
        start_chat: 'Comenzar chat',
        select_friends: 'Selecciona amigos con los que deseas chatear',
        add_friend: 'Añadir como amigo',
        remove_friend: 'Eliminar como amigo',
        confirm_remove_friend: 'Por favor, confirme que desea eliminar como amigo.',
        chat_name: 'Nombre de chat',
        rename_chat: 'Cambiar el nombre del chat',
        send_message: 'Enviar un mensaje',
        enter_pin: 'Introduce el PIN de tu amigo',
        add_member: 'Añadir miembro',
        view_members: 'Ver miembros',
        remove_chat: 'Eliminar chat',
        audio_expired: 'El clip de audio ha caducado'
    },
    notifications: {
        heading: 'Notificaciones',
        sub_heading: 'Estar al día',
        caught_up: '¡Estáis todos atrapados!',

        chat_notification: 'Notificación de chat',
        new_friend_request: 'Nueva solicitud de amistad',
        friend_request_approved: 'Solicitud de amistad aprobada',
        requested_to_be_your_friend: 'pidió ser su amigo.',
        accepted_your_friendship: 'acepto tu amistad.',
        requested_to_check_in: 'Se le ha solicitado que se registre por',
        contact_them: 'Póngase en contacto con ellas por teléfono o mensaje de texto.',
        this_is_emergency_alarm_from: 'Esta es una alarma de emergencia de',
        checked_in_title: 'Registrada',
        has_checked_in: ' se ha registrado.',
        welcome_title: 'Bienvenida',
        welcome_body: 'Bienvenida a myShout'
    },
    gps: {
        gps: 'GPS',
        user_no_location: 'El usuario aún no ha actualizado su ubicación.'
    },
    contacts: {
        invite_friends: 'Invitar a amigas',
        no_contacts: 'no tienes contactos',
        find_friends: 'Buscar amigas',
        search_friends: 'Buscar amigas',
    },
    onboarding: {
        terms_text: 'Al registrarse, aceptas nuestra',
        terms_btn: 'Política de privacidad y términos',
        enable_location_permissions_heading: 'Tu ubicación',
        enable_location_permissions_sub: 'MyShout recopila datos de ubicación para habilitar botones de emergencia, mapeo en la aplicación.',
        enable_notification_permissions_heading: 'Notificaciones',
        enable_notification_permissions: 'Las notificaciones pueden incluir alertas, sonidos e íconos distintivos. Estos se pueden configurar en la configuración.',
        add_phone_number_heading: '¿Cuál es tu número de teléfono?',
        add_phone_number_sub: 'Su número de teléfono es vital para alertar a sus amigos y familiares en caso de emergencia.',
        add_photo_heading: '¡Excelente! ¿Qué tal una foto de perfil?',
        add_photo_sub: 'Deja que otros vean quién eres.',
        profile_setup_heading: '¡Bienvenidas!',
        profile_setup_sub: 'Parece que eres nueva aquí, configuremos tu perfil.',
        register_to_get_started: 'Regístrese para comenzar',
        already_have_account: '¿Ya tienes una cuenta? ¡Acceso!',
        agree_to_terms: 'Sí, estoy de acuerdo con los términos',
        heading_sign_in: '¡Bienvenido de nuevo! Iniciar sesión',
        btn_no_account: '¿No tienes una cuenta? ¡Inscribirse!',
        thank_you_heading: '¡Terminaste!',
        thank_you_sub: 'Gracias por configurar tu perfil.',
        username_heading: '¿Como deberíamos llamarte?',
        username_sub: 'Establezca un nombre para mostrar para que otros sepan con quién están hablando.',
        email_sub: 'Proporcione su dirección de correo electrónico. Esta se utilizará para recuperar su cuenta en caso de que pierda su número de teléfono.',
        error_wrong_password: `La contraseña ingresada es incorrecta.`,
        error_user_not_found: `No existe ningún usuario. Por favor crea una nueva cuenta`,
        error_email_in_use: `La dirección de correo electrónico ya está en uso.`,
        location_description: 'MyShout usa datos de ubicación para notificar a sus contactos de emergencia y a un administrador, si la emergencia está en su nivel más alto. Cuando hace clic en un botón de emergencia, este utilizará sus datos de ubicación GPS más recientes y notificará a sus contactos. Su ubicación siempre se recopila para notificaciones de emergencia, incluso cuando la aplicación se ejecuta en segundo plano. El acceso a la ubicación solo se usa para los mapas para mostrar a sus contactos dónde se encuentra y para enviar notificaciones a los contactos seleccionados.',
        location_requirements_1: 'Al hacer clic en un botón de emergencia para notificar a sus contactos de emergencia',
        location_requirements_2: 'Notificar a sus contactos de emergencia',
        location_requirements_3: 'Habilitar el mapeo en la aplicación',
        location_requirements_4: 'La ubicación se captura incluso mientras se ejecuta en segundo plano',
        notification_requirements_1: 'Para nuevas solicitudes de amistad',
        notification_requirements_2: 'Para notificaciones de chat',
        notification_requirements_3: 'Para alertas de emergencia',
        notification_requirements_4: 'Su micrófono solo se utilizará para Alertas de Grito'
    },
    page: {
        not_found_heading: '404',
        not_found_text: 'Nada Encontrado',

        contact_intro: 'No dudes en comunicarte con nosotros con cualquier pregunta que puedas tener.',
        status_heading_success: '¡Tu cuenta está activa!',
        status_heading_error: '¡Su cuenta no está activa!',

        faq: 'Preguntas más frecuentes',
        home_h1: 'Alertas de emergencia',
        home_p: 'Al presionar cualquiera de las siguientes alertas, notificarás a todos tus contactos de emergencia tu última ubicación conocida.'
    },
    permission: {
        yes_status: 'Tu estado es activo',
        no_status: 'No puede acceder a eso, su estado no es activo.',
        no_user_profile: 'No tienes permiso para ver su perfil.',
        no_view_location: 'No puedes ver su ubicación.'
    },
    chat: {
        admins: 'Administradores',
        members: 'Miembros',
        add_member: 'Añadir miembro',
        mute_notifications: 'Silenciar notificaciones',
        unmute_notifications: 'Activar notificaciones',
        view_profile: 'Ver Perfil',  
        leave_group: 'Salir del Grupo',
        remove_from_group: 'Eliminar del Grupo',
        leave_chat: 'Salir del Chat',
        add_title: 'ajouter un titre',
        add_group_description: 'ajouter une description de groupe',
        error_updating: 'Hubo un problema al actualizar...',
        message_deleted: 'This message was deleted',
        delete_for_me: 'Eliminar para mí',
        delete_for_everyone: 'Eliminar para todos',
        info: 'Info',
        thread: 'Ver hilo'
    },

    no_results: 'No hay resultados',
    actions: 'Acciones',
    is_loading: 'Cargando...',
    copyright: 'Derechos de autor',
    you_are_currently_logged_in: '¡Usted está actualmente conectado!',
    you_are_currently_offline: '¡UH oh! Parece que estás desconectado.',
    not_supposed_to_be_here: 'Parece que no deberías estar aquí.',
    page_not_found: 'Página no encontrada',
    error_occurred: 'Ocurrió un error',
    refresh_data: 'Intenta actualizar datos',

    profile: 'Perfil',
    view_profile: 'Ver perfil',
    view_more: 'Ver más',

    know_your_safe: '¡Hazle saber a tus familiares y amigos que estás a salvo!',
    include_email: 'Incluyamos tu correo electrónico para una copia de seguridad.',
    new_friend_request: 'Nueva solicitud de amistad',
    requested_to_be_your_friend: 'pidió ser su amigo.',
    skip_for_now: 'Saltar por ahora',
    start_chatting: 'Proporciona tu número de teléfono para comenzar a chatear',
    security_pin_heading: 'Pin de seguridad',
    security_pin_description: 'Proporciona tu PIN secreto a aquellos que deseas agregar como amigos en My-Shout',

    emergency_contacts_heading: 'Contactos de emergencia',
    emergency_contacts_description: 'Obligatorio, comparte tu ubicación con todos los contactos de emergencia',
    all_friends_header: 'Todos los amigos',
    all_friends_description: 'Opcionalmente, comparte tu ubicación con todos los aprobados…',

    must_be_emergency_contact: 'Debe ser su contacto de emergencia para ver las alertas',
    you_have_no_alerts: 'No tienes alertas',

    verify_account: 'Inicie sesión nuevamente para verificar su cuenta',
    already_verified: 'Su cuenta ya está vinculada con un correo electrónico',

    remove_friend: 'Eliminar como amigo',
    friendship_is: 'amistad es',
    location: 'Ubicación',
    alerts: 'Alertas',
    emergency: 'Emergencia',
    friends: 'Amigas',
    settings: 'Ajustes',

    alert: 'Alerta',
    accident: 'Accidente',
    kidnapping: 'Secuestro',
    robbery: 'Robo',
    shout: 'Grito',

    alert_details: 'Detalles de la alerta',
    accident_alert: 'Alerta de accidente',
    kidnapping_alert: 'Alerta de secuestro',
    robbery_alert: 'Alerta de robo',
    shout_alert: 'Alerta de grito',
    your_shout_alert: 'Tu alerta de Grito ha sido enviada',
    hold_for: 'Mantén presionado para enviar una grabación de audio de 5 segundos',
    alert_sent: 'Alerta enviada',
    notified_emergency_contacts_accident: 'Hemos notificado a sus contactos de emergencia de su accidente. Por favor llámelos tan pronto como tenga la oportunidad.',
    notified_emergency_contacts_kidnapping: 'Hemos notificado a sus contactos de emergencia de su secuestro. Por favor llámelos tan pronto como tenga la oportunidad.',
    notified_emergency_contacts_robbery: 'Hemos notificado a sus contactos de emergencia de su robo. Por favor llámelos tan pronto como tenga la oportunidad.',

    recording: 'Grabación',

    previous: 'Previa',
    next: 'Próxima',

    sharing_your_location_sub: 'Compartir su ubicación es fundamental para que los contactos de emergencia controlen su ubicación.',
    receive_notifications_sub: 'Reciba notificaciones cuando un amigo tenga problemas o cuando se reciba un nuevo mensaje de chat.',

    check_in: 'Registrarse',
    request_safe_check_in: 'Solicitar ingreso seguro',
    confirm_they_are_safe: 'Enviaremos una alerta para confirmar que son seguros.',
    remove_as_emergency_contact: 'Eliminar como contacto de emergencia',
    add_as_emergency_contact: 'Agregar como contacto de emergencia',
    no_longer_receive_alerts: 'Ya no recibirán alertas cuando tenga problemas.',
    yes_longer_receive_alerts: 'Recibirán alertas cuando tengas problemas.',
    view_on_list: 'Ver en la lista',

    no_emergency_friends: 'You have no emergency friends',

    use_email_address: 'Usar dirección de correo electrónico',
    use_phone_number: 'Usar número de teléfono'
}

