export default {
    btn: {
        load_new: 'Charger nouveau',
        delete_all: 'Supprimer tout',
        back: 'Retour',
        back_to_login: 'Retour connexion',
        save: 'Enregistrer',
        delete: 'Effacer',
        download: 'Télécharger',
        send: 'Envoyer',
        retry: 'Recommencez',
        add: 'Ajouter',
        cancel: 'Annuler',
        confirm: 'Confirmer',
        yes_delete: 'Oui, supprimer',
        yes_i_agree: 'Oui je suis d\'accord',
        close: 'Fermer',
        edit: 'Éditer',
        remove: 'Retirer',
        yes_remove: 'Oui, supprimer',
        send_code: 'Envoyer Le Code',
        register: 'S\'inscrire',
        register_no_account: 'Vous n\'avez pas de compte ? S\'inscrire',
        forgot_password: 'Mot de passe oublié?',
        already_have_account: 'Vous avez déjà un compte? Connexion',
        location_permissions: 'Permission de localisation',
        notification_permissions: 'Permission de notification',
        account_settings: 'Paramètres du compte',
        about_us: 'À propos de nous',
        contact_us: 'Nous contacter',
        language: 'Langue',
        help_center: 'Centre d\'aide',
        frequent_questions: 'Questions fréquentes',
        feedback: 'Commentaires',
        privacy_terms: 'Conditions générales et Politique de confidentialité',
        admin: 'Administratrice',
        admin_sub: 'Gérez vos données',
        edit_profile: 'Modifier le profil',
        edit_profile_sub: 'Mettez à jour vos informations',
        settings_privacy: 'Paramètres et confidentialité',
        settings_privacy_sub: 'Permissions, paramètres, confidentialité',
        log_out: 'Déconnexion',
        log_out_sub: 'Se déconnecter ou changer de compte',
        login: 'Connexion',
        verify: 'Vérifier',
        sign_up: `S'inscrire`,
        dark_mode: 'Mode sombre',
        learn_more: 'Apprendre encore plus',
        content: 'Contenu',
        back_to_app: 'Vers l\'application',
        send_password_reset: 'Envoyer la réinitialisation du mot de passe',
        deactivate: 'Désactiver',
        reactivate: 'Réactiver',
        confirm_request: 'Confirmer la requête',
        recent_chats: 'Chats Récents'
    },
    notify: {
        no_audio: 'Pas de son',
        success: 'Succès',
        check_your_email: 'Merci de consulter vos emails',
        error_try_again: 'Erreur, réessayez',
        exists_already: 'Existe déjà',
        email_in_use: 'Email déjà utilisé',
        phone_in_use: 'Téléphone déjà utilisé',
        username_in_use: 'Nom d\'utilisateur déjà utilisé',
        already_linked: 'Votre compte est déjà lié',
        agree_to_terms: 'Vous devez accepter les conditions avant de continuer',
        validate_your_phone: 'Vous devez valider votre numéro de téléphone avant de continuer',

        not_enough_admins: 'Le chat doit avoir au moins un administrateur.',

        gps_permission_denied: 'Emplacement d\'autorisation refusé',
        gps_permission_prompt: 'Invite d\'emplacement d\'autorisation',

        file_uploaded_error_type: 'Erreur, pas un type de fichier approprié',

        notifications_not_supported: 'Les notifications ne sont pas prises en charge',
        notifications_error: 'Erreur avec vos notifications',

        pin_no_match: 'Ce code PIN ne correspond pas',

        are_you_sure: 'Êtes-vous sûr?',
        please_confirm_delete: 'Veuillez confirmer que vous souhaitez supprimer votre compte et toutes les données. Ce n\'est pas réversible.'
    },
    heading: {
        login_phone: `Veuillez fournir votre numéro de téléphone pour vous connecter`,
        login_email: `Fournissez votre adresse email pour vous connecter`,
        signup_phone: `Fournissez votre numéro de téléphone pour créer un compte`,
        signup_email: `Veuillez fournir votre adresse email pour créer un compte`,
        cant_receive_sms_code: 'Vous ne pouvez pas recevoir de code ? Se connecter par e-mail',
        we_sent_you_sms_code: 'Nous vous avons envoyé un code SMS',
        forgot_password: 'Mot de passe oublié',
        edit_profile: 'Profil',
        change_language: 'Changer de langue',
        add_email: 'Ajouter votre adresse e-mail',
        register: 'Inscription gratuite',
        change_email_address: 'Modifier l’adresse e-mail',
        change_email_address_caption: 'Pour changer votre email, veuillez fournir votre mot de passe.',
        change_password: 'Modifier le mot de passe',
        change_password_caption: 'Pour changer votre mot de passe, veuillez fournir votre mot de passe actuel.',
        change_phone_number: 'Changer de numéro de téléphone',
        change_phone_number_caption: 'Pour changer de téléphone, veuillez fournir votre OTP qui vous a été envoyé.',
        delete_account: 'Supprimer le compte',
        delete_account_caption: 'L’ensemble de votre profil et de vos données sera définitivement supprimé.',
        friends: 'Amies',
        login: 'Connexion'
    },
    form: {
        first_name: 'Prénom',
        last_name: 'Nom',
        name: 'Nom',
        username: 'Nom d\'utilisateur',
        description: 'La description',
        hometown: 'Ville de résidence',
        country: 'Pays',
        email: 'E-mail',
        phone: 'Téléphone',
        confirm_password: 'Confirmez le mot de passe',
        message: 'Message',
        password: 'Mot de passe',
        current_password: 'Mot de passe actuel',
        new_password: 'Nouveau mot de passe',
        search_for_address: 'Rechercher votre adresse',
        search: 'Chercher',
        search_friends: 'Rechercher des amis...',
        code: 'Code',
        company: 'Compagnie',
        tags: 'Mots clés',
        images: 'Images',
        website: 'Site Internet',
        address: 'Adresse',
        city: 'Ville',
        province: 'Province',
        postal_code: 'code postal',
        published: 'Publié',
        logo: 'Logo',
        featured_image: 'L\'image sélectionnée',
        featured_category: 'Catégorie en vedette',
        tag: 'Étiquette',
        title: 'Titre',
        content: 'Contenu',
        using_markdown: 'Le contenu utilise-t-il le démarquage ?',
        learn_more_url: 'En savoir plus',
        learn_more_label: 'En savoir plus Étiquette',
        is_admin: 'Est administrateur',
        created_at: 'Créé à',
        location_enabled: 'Emplacement activé',
        share_location: 'Emplacement partagé',
        pin: 'PIN',
        filter_by: 'Filtrer par'
    },
    email: {
        contact_h1: 'You were contacted'
    },
    chats: {
        page_h1: 'Vos chats',
        no_chats: 'Aucun chat à afficher',
        no_messages: 'Envoyez le premier message !',
        label_message: 'Message',
        select_friend_first: 'Sélectionnez d\'abord un ami',
        no_friends: 'Vous n\'avez pas d\'amis avec qui discuter.',
        new_chat: 'Nouveau chat',
        start_chat: 'Démarrer le chat',
        select_friends: 'Sélectionnez les amis avec lesquels vous souhaitez chatter',
        add_friend: 'Ajouter comme ami',
        remove_friend: 'Supprimer des amis',
        confirm_remove_friend: 'Veuillez confirmer que vous souhaitez supprimer en tant qu\'ami.',
        chat_name: 'nom du chat',
        rename_chat: 'Renommer le chat',
        send_message: 'Envoyer un message',
        enter_pin: 'Enter in your friend\'s PIN',
        add_member: 'Ajouter membre',
        view_members: 'Voir les membres',
        remove_chat: 'Supprimer le chat',
        audio_expired: 'Le clip audio a expiré',
        you_replied_to: 'Vous avez répondu à',
        replying_to: 'Répondre à',
        forward: 'Avant',
        video_not_supported: 'Vidéos non prises en charge'
    },
    notifications: {
        heading: 'Avis',
        sub_heading: 'Tiens-toi à jour',
        caught_up: 'Vous êtes tous rattrapés !',

        chat_notification: 'Notification de chat',
        new_friend_request: 'Nouvelle demande d\'ami',
        friend_request_approved: 'Demande d\'ami approuvée',
        requested_to_be_your_friend: 'demandé à être ton ami.',
        accepted_your_friendship: 'accepté votre amitié.',
        requested_to_check_in: 'Vous avez été invité à vous enregistrer par',
        contact_them: 'Contactez-les par téléphone ou SMS.',
        this_is_emergency_alarm_from: 'Ceci est une alarme d\'urgence de',
        checked_in_title: 'Enregistrée',
        has_checked_in: ' s\'est enregistré.',
        welcome_title: 'Bienvenue',
        welcome_body: 'Bienvenue sur MyShout'
    },
    gps: {
        gps: 'GPS',
        user_no_location: 'L\'utilisateur n\'a pas encore mis à jour sa position.',
        rationale_title: 'Autorisez My Shout à accéder à l\'emplacement de cet appareil même lorsqu\'il est fermé ou non utilisé.',
        rationale_message: 'Cette application collecte des données de localisation pour informer votre famille et vos contacts d\'urgence en cas d\'urgence.',
        rationale_positive_action: 'Changer pour Toujours autoriser',
        rationale_negative_action: 'Annuler'
    },
    contacts: {
        invite_friends: 'Inviter des amis',
        no_contacts: 'Vous n\'avez aucun contact',
        find_friends: 'Trouver des amis',
        search_friends: 'Rechercher des amis',
    },
    onboarding: {
        terms_text: 'En vous inscrivant, vous acceptez nos',
        terms_btn: 'Politique de confidentialité et conditions',
        enable_location_permissions_heading: 'Votre emplacement',
        enable_location_permissions_sub: 'MyShout collecte des données de localisation pour activer les boutons d\'urgence, la cartographie in-app.',
        enable_notification_permissions_heading: 'Avis',
        enable_notification_permissions: 'Les notifications peuvent inclure des alertes, des sons et des badges d\'icônes. Ceux-ci peuvent être configurés dans les paramètres.',
        add_phone_number_heading: 'Quel est votre numéro de téléphone?',
        add_phone_number_sub: 'Votre numéro de téléphone est essentiel pour alerter vos amis et votre famille en cas d\'urgence.',
        add_photo_heading: 'Super! Que diriez-vous d\'une photo de profil ?',
        add_photo_sub: 'Laissez les autres voir qui vous êtes.',
        profile_setup_heading: 'Bienvenue!',
        profile_setup_sub: 'On dirait que vous êtes nouveau ici, configurons votre profil.',
        register_to_get_started: 'Inscrivez-vous pour commencer',
        already_have_account: 'Vous avez déjà un compte? Connexion!',
        agree_to_terms: 'Oui, j’accepte les conditions',
        heading_sign_in: 'Content de te revoir! S\'identifier',
        btn_no_account: 'Vous n\'avez pas de compte ? S\'inscrire!',
        thank_you_heading: 'Vous avez terminé!',
        thank_you_sub: 'Merci d\'avoir créé votre profil.',
        username_heading: 'Comment doit-on vous appelez?',
        username_sub: 'Définissez un nom d\'affichage pour que les autres sachent à qui ils parlent.',
        email_sub: 'Fournissez votre adresse e-mail. Elle sera utilisée pour récupérer votre compte en cas de perte de votre numéro de téléphone.',
        error_wrong_password: `Le mot de passe saisi est incorrect.`,
        error_user_not_found: `Aucun utilisateur n'existe. Veuillez créer un nouveau compte.`,
        error_email_in_use: `L'adresse email est déjà utilisée.`,
        location_description: 'MyShout utilise les données de localisation pour informer vos contacts d\'urgence et un admin, si l\'urgence est au plus haut niveau. Lorsque vous cliquez sur un bouton d\'urgence, celui-ci utilise vos dernières données de localisation GPS et avertit vos contacts. Votre position est toujours collectée pour les notifications d\'urgence, même lorsque l\'application s\'exécute en arrière-plan. L\'accès à la localisation n\'est utilisé que pour les cartes afin de montrer à vos contacts où vous vous trouvez et d\'envoyer des notifications aux contacts sélectionnés.',
        location_requirements_1: 'Lorsque vous cliquez sur un bouton d\'urgence pour avertir vos contacts d\'urgence',
        location_requirements_2: 'Aviser vos contacts d\'urgence',
        location_requirements_3: 'Activer le mappage dans l\'application',
        location_requirements_4: 'L\'emplacement est capturé même lors de l\'exécution en arrière-plan',
        notification_requirements_1: 'Pour les demandes de nouveaux amis',
        notification_requirements_2: 'Pour les notifications de chat',
        notification_requirements_3: 'Pour les alertes d\'urgence',
        notification_requirements_4: 'Votre microphone ne sera utilisé que pour les alertes Shout'
    },
    page: {
        not_found_heading: '404',
        not_found_text: 'Rien n\'a été trouvé',

        contact_intro: 'N’hésitez pas à nous contacter pour toute question que vous pourriez avoir.',
        status_heading_success: 'Votre compte est actif !',
        status_heading_error: 'Votre compte n\'est pas actif!',

        faq: 'FAQ',
        home_h1: 'Alertes d’urgence',
        home_p: 'En appuyant sur l’une alertes suivantes, vous enverrez à tous vos contacts d’urgence votre dernière localisation connue.'
    },
    permission: {
        yes_status: 'Votre statut est actif',
        no_status: 'Vous ne pouvez pas y accéder, votre statut n\'est pas actif.',
        no_user_profile: 'Vous n\'êtes pas autorisé à voir leur profil.',
        no_view_location: 'Vous ne pouvez pas voir leur emplacement.'
    },
    chat: {
        admins: 'Admins',
        members: 'Membres',
        mute_notifications: 'Désactiver les notifications',
        unmute_notifications: 'Activer les notifications',
        add_member: 'Ajouter un membre',
        view_profile: 'Voir le profil',
        leave_group: 'Quitter le groupe',
        remove_from_group: 'Retirer du groupe',
        remove_from_chat: 'Retirer du Chat',
        leave_chat: 'Quitter le chat',
        add_title: 'ajouter un titre',
        add_group_description: 'ajouter une description de groupe',
        error_updating: 'Il y a eu un problème lors de la mise à jour...',
        message_deleted: 'This message was deleted',
        delete_for_me: 'Supprimer pour moi',
        delete_for_everyone: 'Supprimer pour tout le monde',
        info: 'Info',
        thread: 'Voir la discussion',
        message_thread: 'Fil de Messages',
        forward_to: 'Transférer à',
        download_file: 'élécharger le fichier',
        refresh_chat: 'Actualiser la discussion'
    },

    no_results: 'Aucun résultat',
    actions: 'Actions',
    is_loading: 'Chargement...',
    copyright: 'droits d\'auteur',
    you_are_currently_logged_in: 'Vous êtes actuellement connecté!',
    you_are_currently_offline: 'Euh Oh ! Il semble que vous soyez hors ligne.',
    not_supposed_to_be_here: 'On dirait que vous n\'êtes pas censé être ici.',
    page_not_found: 'Page non trouvée',
    error_occurred: 'Une erreur s\'est produite',
    refresh_data: 'Essayez d\'actualiser les données',

    profile: 'Profil',
    view_profile: 'Voir le profil',
    view_more: 'Voir plus',

    know_your_safe: 'Dites à votre famille et vos amis que vous êtes en sécurité !',
    include_email: 'Incluons votre email pour une sauvegarde',
    new_friend_request: 'Nouvelle demande d\'ami',
    requested_to_be_your_friend: 'demandé à être ton ami.',
    skip_for_now: 'Ignorer pour l\'instant',
    start_chatting: 'Saisissez votre numéro de téléphone pour commencer à chatter',
    security_pin_heading: 'Code PIN de sécurité',
    security_pin_description: 'Fournissez votre code PIN secret aux personnes qui souhaitent vous ajouter en tant qu’ami sur My-Shout.',

    emergency_contacts_heading: 'Contacts d’urgence',
    emergency_contacts_description: 'Obligatoire, partagez votre position avec tous les contacts d’urgence',
    all_friends_header: 'Tous les amis',
    all_friends_description: 'En option, vous pouvez partager votre position avec tous les approuvés.',

    must_be_emergency_contact: 'Vous devez être leur contact d\'urgence pour voir les alertes',
    you_have_no_alerts: 'Vous n\'avez aucune alerte',

    verify_account: 'Veuillez vous reconnecter pour vérifier votre compte',
    already_verified: 'Votre compte est déjà lié à un e-mail',

    remove_friend: 'Supprimer en tant qu\'ami',
    friendship_is: 'l\'amitie c\'est',
    location: 'Localisation',
    alerts: 'Alertes',
    emergency: 'Urgence',
    friends: 'Amies',
    settings: 'Paramètres',

    alert: 'Alerte',
    accident: 'Accident',
    kidnapping: 'Enlèvement',
    robbery: 'Vol',
    shout: 'Cri',

    alert_details: 'Détails de l\'alerte',
    accident_alert: 'Alerte accident',
    kidnapping_alert: 'Alerte enlèvement',
    robbery_alert: 'Alerte vol',
    shout_alert: 'Cri d’Alarme',
    your_shout_alert: 'Votre alerte Shout a été envoyée',
    hold_for: 'Appuyer pour envoyer un enregistrement audio de 5 secondes',
    alert_sent: 'Alerte envoyée',
    notified_emergency_contacts_accident: 'Nous avons informé vos contacts d\'urgence de votre accident. Veuillez les appeler dès que vous en avez l\'occasion.',
    notified_emergency_contacts_kidnapping: 'Nous avons informé vos contacts d\'urgence de votre enlèvement. Veuillez les appeler dès que vous en avez l\'occasion.',
    notified_emergency_contacts_robbery: 'Nous avons informé vos contacts d\'urgence de votre vol. Veuillez les appeler dès que vous en avez l\'occasion.',

    recording: 'Enregistrement',

    previous: 'Précédente',
    next: 'Prochaine',

    sharing_your_location_sub: 'Le partage de votre position est essentiel pour que les contacts d\'urgence puissent surveiller votre position.',
    receive_notifications_sub: 'Recevez des notifications lorsqu\'un ami est en difficulté ou qu\'un nouveau message de chat a été reçu.',

    check_in: 'Enregistrement',
    request_safe_check_in: 'Demander un check-in sécurité',
    confirm_they_are_safe: 'Nous enverrons une alerte pour confirmer qu\'ils sont en sécurité.',
    remove_as_emergency_contact: 'Supprimer des contacts d’urgence',
    add_as_emergency_contact: 'Ajouter comme contact d’urgence',
    no_longer_receive_alerts: 'Ils ne recevront plus d\'alertes lorsque vous rencontrez des problèmes.',
    yes_longer_receive_alerts: 'Ils recevront des alertes lorsque vous êtes en difficulté.',
    view_on_list: 'Voir sur liste',

    no_emergency_friends: 'Vous n\'avez pas d\'amis d\'urgence',

    use_email_address: 'Utiliser l\'adresse e-mail',
    use_phone_number: 'Utiliser le numéro de téléphone'
}

